dist:
  name: otelcol-dev
  description: Basic OTel Collector distribution for Developers
  output_path: ./otelcol-dev

    
exporters:
  - gomod:
      go.opentelemetry.io/collector/exporter/loggingexporter v0.73.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/exporter/jaegerexporter
      v0.73.0

processors:
  - gomod:
      go.opentelemetry.io/collector/processor/batchprocessor v0.73.0

receivers:
  - gomod:
      go.opentelemetry.io/collector/receiver/otlpreceiver v0.73.0
  - gomod:
      github.com/liatrio/ldapreceiver
